function patientselect = choosedialog
    d = dialog('Position',[300 300 250 150],'Name','Select Patient');
    
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 80 210 40],...
           'String','Select a Patient');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 70 100 25],...
           'String',{'IRST001';'IRST002';'IRST003';'IRST004';'IRST005';...
           'IRST007';'IRST008';'IRST009';'IRST010';'IRST011';'IRST012';...
           'IRST013';'IRST014';'IRST015';},... %ADD NEW PATIENTS HERE
           'Callback',@popup_callback);
       
    btn = uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','Next',...
           'Callback','delete(gcf)');     
   
    patientselect = 'IRST001';
       
    % Wait for d to close before running to completion
    uiwait(d);
   
       function popup_callback(popup,event)
          idx = popup.Value;
          popup_items = popup.String;
          patientselect = char(popup_items(idx,:));
       end
end