function volunteerselect = choosedialog
    d = dialog('Position',[300 300 250 150],'Name','Select Patient');
    
    txt = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 80 210 40],...
           'String','Select a Patient');
       
    popup = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 70 100 25],...
           'String',{'IRVT001';'IRVT002';'IRVT003';'IRVT004';'IRVT005';...
           'IRVT007';'IRVT008';'IRVT009';'IRVT010';'IRVT011';'IRVT012';...
           'IRVT013';'IRVT014';'IRVT015';'IRVT016';'IRVT017';'IRVT301';...
           'IRVT302';'IRVT303';'IRCT304';'IRVT305';'IRVT306';'IRVT307'},...
           'Callback',@popup_callback); %ADD NEW VOLUNTEERS HERE^^
       
    btn = uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','Next',...
           'Callback','delete(gcf)');     
   
    volunteerselect = 'IRVT001';
       
    % Wait for d to close before running to completion
    uiwait(d);
   
       function popup_callback(popup,event)
          idx = popup.Value;
          popup_items = popup.String;
          volunteerselect = char(popup_items(idx,:));
       end
end